from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, FloatField, SubmitField, HiddenField, BooleanField, SelectField, IntegerField
from wtforms.validators import DataRequired, URL, Optional, Length, NumberRange

class ProductForm(FlaskForm):
    """Form for adding or editing a product."""
    title = StringField('Title', validators=[DataRequired(), Length(max=255)])
    description = TextAreaField('Description', validators=[Optional()])
    price = FloatField('Price', validators=[Optional()])
    image_url = StringField('Image URL', validators=[Optional(), URL()])
    submit = SubmitField('Save')

class EnvVarForm(FlaskForm):
    """Form for adding or editing environment variables."""
    key = StringField('Key', validators=[DataRequired(), Length(max=255)])
    value = StringField('Value', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[Optional()])
    submit = SubmitField('Save')

class CollectionForm(FlaskForm):
    """Form for creating or editing a collection."""
    name = StringField('Name', validators=[DataRequired(), Length(max=255)])
    slug = StringField('Slug', validators=[Optional(), Length(max=255)])
    description = TextAreaField('Description', validators=[Optional()])
    meta_description = TextAreaField('Meta Description (for SEO)', validators=[Optional(), Length(max=160)])
    tag_id = HiddenField('Tag ID')
    submit = SubmitField('Save')

class TagForm(FlaskForm):
    """Form for adding a tag manually."""
    name = StringField('Name', validators=[DataRequired(), Length(max=100)])
    submit = SubmitField('Add Tag')

class AutoTagForm(FlaskForm):
    """Form for auto-tagging products."""
    submit = SubmitField('Auto-Tag Selected Products')

class CreateCollectionsForm(FlaskForm):
    """Form for creating collections from tags."""
    exclude_imported_tags = BooleanField('Only use tags generated by Claude (exclude imported tags)')
    submit = SubmitField('Create Collections from Tags')

class StoreForm(FlaskForm):
    """Form for adding or editing a store."""
    name = StringField('Store Name', validators=[DataRequired(), Length(max=255)])
    url = StringField('Store URL', validators=[DataRequired(), Length(max=255)])
    access_token = StringField('Access Token', validators=[Optional(), Length(max=255)])
    submit = SubmitField('Save')

class StoreSelectForm(FlaskForm):
    """Form for selecting the current store."""
    store_id = SelectField('Select Store', coerce=int)
    submit = SubmitField('Switch Store')

class CleanupRuleForm(FlaskForm):
    """Form for adding or editing cleanup rules."""
    pattern = StringField('Pattern to Find', validators=[DataRequired(), Length(max=255)])
    replacement = StringField('Replace With', validators=[DataRequired(message="Replacement cannot be empty, use '' for removing."), Length(max=255)])
    is_regex = BooleanField('Use Regular Expression')
    priority = IntegerField('Priority (Lower number runs first)', default=0, validators=[Optional(), NumberRange(min=0)])
    submit = SubmitField('Save Rule')
