"""Add SEO fields and SEODefaults model

Revision ID: 142f42794f63
Revises: 
Create Date: 2025-04-01 12:16:02.560320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142f42794f63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))
        batch_op.alter_column('meta_description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=160),
               existing_nullable=True)
        batch_op.alter_column('structured_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('cleaned_title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('structured_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('structured_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('cleaned_title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.alter_column('structured_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('meta_description',
               existing_type=sa.String(length=160),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
