"""Add BlogPost model and Store enhancements for blog generation

Revision ID: 3dcd1fb07a00
Revises: 6548b59c7de6
Create Date: 2025-04-03 19:55:59.851386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dcd1fb07a00'
down_revision = '6548b59c7de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_audience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tone_of_voice', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sitemap_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('sitemap_url')
        batch_op.drop_column('tone_of_voice')
        batch_op.drop_column('target_audience')

    # ### end Alembic commands ###
