"""Add is_app_managed flag to Tag model

Revision ID: 45470bbce6d7
Revises: 142f42794f63
Create Date: 2025-04-02 23:02:45.645348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45470bbce6d7'
down_revision = '142f42794f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_app_managed', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('is_app_managed')

    # ### end Alembic commands ###
