"""Add concept and keyword_map to Store

Revision ID: 6548b59c7de6
Revises: 45470bbce6d7
Create Date: 2025-04-03 11:43:34.778616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6548b59c7de6'
down_revision = '45470bbce6d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('concept', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('keyword_map', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('keyword_map')
        batch_op.drop_column('concept')

    # ### end Alembic commands ###
